name: "Heal Trigger Action"
description: "Trigger a Heal suite execution and optionally wait for results"
author: "Heal.dev"

inputs:
  api-token:
    description: "Heal API token"
    required: true
  suite-id:
    description: "Suite ID to trigger"
    required: true
  payload:
    description: "Optional payload in JSON format"
    required: false
    default: "{}"
  wait-for-results:
    description: "Wait for the execution to finish (yes/no)"
    required: false
    default: "yes"
  domain:
    description: "Domain for Heal API (default: https://app.heal.dev)"
    required: false
    default: "https://app.heal.dev"
  comment-on-pr:
    description: "Whether to comment test results on PR (yes/no)"
    required: false
    default: "no"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install Dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        npm ci

    - name: Run Heal Tests
      shell: node
      working-directory: ${{ github.action_path }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        HEAL_API_TOKEN: ${{ inputs.api-token }}
        HEAL_SUITE_ID: ${{ inputs.suite-id }}
        HEAL_PAYLOAD: ${{ inputs.payload }}
        HEAL_WAIT_FOR_RESULTS: ${{ inputs.wait-for-results }}
        HEAL_DOMAIN: ${{ inputs.domain }}
        HEAL_COMMENT_ON_PR: ${{ inputs.comment-on-pr }}
      run: ./dist/index.js
