name: 'Heal Trigger Action'
description: 'Trigger a Heal suite execution and optionally wait for results'
author: 'Heal.dev'
inputs:
  api-token:
    description: 'Heal API token'
    required: true
  suite-id:
    description: 'Suite ID to trigger'
    required: true
  payload:
    description: 'Optional payload in JSON format'
    required: false
    default: '{}'
  wait-for-results:
    description: 'Wait for the execution to finish (yes/no)'
    required: false
    default: 'yes'
  domain:
    description: 'Domain for Heal API (default: https://app.heal.dev)'
    required: false
    default: 'https://app.heal.dev'
  github-token:
    description: 'GitHub token for PR comments (optional)'
    required: false
    default: ''
  comment-on-pr:
    description: 'Whether to comment test results on PR (yes/no)'
    required: false
    default: 'no'
outputs:
  execution-id:
    description: 'ID of the test suite execution'
  execution-url:
    description: 'URL of the test suite execution'

runs:
  uses: actions/setup-node@v4
    with:
      node-version: 22
  main: './index.js'
